project_id = "jschuymzkukzthesevoy"

[functions.vps-monitor-sync]
verify_jwt = false

[functions.discord-sync]
verify_jwt = false

[functions.cleanup-crossings]
verify_jwt = false

[functions.mexc-arbitrage-monitor]
verify_jwt = false
